<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_model');
    } 

    /*
     * Listing of admin
     */
    function index()
    {
        $data['admin'] = $this->Admin_model->get_all_admin();
        
        $data['_view'] = 'admin/index';
        $this->load->view('layouts/main',$data);
    }

    function detail(){
        $id = $this->input->post('id');
        $data['detail'] =  $this->Admin_model->getDetail($id);
        $this->load->view('profile/profile', $data);
    }
    /*
     * Adding a new admin
     */

    function tambah(){

        $data['_view'] = 'admin/add';
        $this->load->view('layouts/main',$data);
    }
    function add()
    {   
        $config['upload_path'] = './uploads/';
        $config['allowed_types'] = 'gif|jpg|png';
        $config['max_size']  = '2000';
        $this->upload->initialize($config);
        $this->load->library('upload', $config);
        
        if (  $this->upload->do_upload('foto')){
            if($this->Admin_model->add_admin($this->upload->data()) == TRUE){
                redirect('admin/index');
            } else {
                redirect('admin/tambah');
            }
        } else {
            $this->session->set_flashdata('failed', $this->upload->display_errors());
            redirect('admin/tambah');
        }
        
    }  

    /*
     * Editing a admin
     */
    function edit($id)
    {   
        // check if the admin exists before trying to edit it
        $data['admin'] = $this->Admin_model->get_admin($id);
        
        if(isset($data['admin']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'username' => $this->input->post('username'),
					'fullname' => $this->input->post('fullname'),
					'role' => $this->input->post('role'),
					'foto' => $this->input->post('foto'),
					'alamat' => $this->input->post('alamat'),
					'last_login' => $this->input->post('last_login'),
                );

                $this->Admin_model->update_admin($id,$params);            
                redirect('admin/index');
            }
            else
            {
                $data['_view'] = 'admin/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The admin you are trying to edit does not exist.');
    } 

    /*
     * Deleting admin
     */
    function remove($id)
    {
        $admin = $this->Admin_model->get_admin($id);

        // check if the admin exists before trying to delete it
        if(isset($admin['id']))
        {
            $this->Admin_model->delete_admin($id);
            redirect('admin/index');
        }
        else
            show_error('The admin you are trying to delete does not exist.');
    }
    
}
