<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pembayaran extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pembayaran_model');
    } 

    /*
     * Listing of pembayaran
     */
    function index()
    {
        $data['pembayaran'] = $this->Pembayaran_model->get_all_pembayaran();
        
        $data['_view'] = 'pembayaran/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pembayaran
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tanggal_bayar' => $this->input->post('tanggal_bayar'),
				'id_tagihan' => $this->input->post('id_tagihan'),
				'jumlah_tagihan' => $this->input->post('jumlah_tagihan'),
				'biaya_denda' => $this->input->post('biaya_denda'),
				'biaya_admin' => $this->input->post('biaya_admin'),
				'status' => $this->input->post('status'),
            );
            
            $pembayaran_id = $this->Pembayaran_model->add_pembayaran($params);
            redirect('pembayaran/index');
        }
        else
        {            
            $data['_view'] = 'pembayaran/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pembayaran
     */
    function edit($id)
    {   
        // check if the pembayaran exists before trying to edit it
        $data['pembayaran'] = $this->Pembayaran_model->get_pembayaran($id);
        
        if(isset($data['pembayaran']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tanggal_bayar' => $this->input->post('tanggal_bayar'),
					'id_tagihan' => $this->input->post('id_tagihan'),
					'jumlah_tagihan' => $this->input->post('jumlah_tagihan'),
					'biaya_denda' => $this->input->post('biaya_denda'),
					'biaya_admin' => $this->input->post('biaya_admin'),
					'status' => $this->input->post('status'),
                );

                $this->Pembayaran_model->update_pembayaran($id,$params);            
                redirect('pembayaran/index');
            }
            else
            {
                $data['_view'] = 'pembayaran/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pembayaran you are trying to edit does not exist.');
    } 

    /*
     * Deleting pembayaran
     */
    function remove($id)
    {
        $pembayaran = $this->Pembayaran_model->get_pembayaran($id);

        // check if the pembayaran exists before trying to delete it
        if(isset($pembayaran['id']))
        {
            $this->Pembayaran_model->delete_pembayaran($id);
            redirect('pembayaran/index');
        }
        else
            show_error('The pembayaran you are trying to delete does not exist.');
    }
    
}
