<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get admin by id
     */
    function get_admin($id)
    {
        return $this->db->get_where('admin',array('id'=>$id))->row_array();
    }

    public function getDetail($id){
        return $this->db->where('id', $id)->get('admin')->row();
    }
    /*
     * Get all admin
     */
    function get_all_admin()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('admin')->result_array();
    }
        
    /*
     * function to add new admin
     */
    function check_noreg()
{   
     $noreg = $this->input->post('noreg');
    $this->db->where('noreg',$noreg);
    $query = $this->db->get('noreg');
    if ($query->num_rows() > 0){
        return true;
    }
    else{
        return false;
    }
}
    function add_admin($foto)
    {
        $now=date('d-m-Y H:i:s');
         $data = array(
                'password' => $this->input->post('password'),
                'username' => $this->input->post('username'),
                'fullname' => $this->input->post('fullname'),
                'role' => $this->input->post('role'),
                'foto' => $foto['file_name'],
                'alamat' => $this->input->post('alamat'),
                'last_login' => $now,
            );
        $this->db->insert('admin',$data);
        if ($this->db->affected_rows() > 0) {
            return TRUE;            
        } else {
            return FALSE;
        }
    }
    
    /*
     * function to update admin
     */
    function update_admin($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('admin',$params);
    }
    
    /*
     * function to delete admin
     */
    function delete_admin($id)
    {
        return $this->db->delete('admin',array('id'=>$id));
    }
}
